const world=document.getElementById('world');const camera=document.getElementById('camera');const player=document.getElementById('player');const log=document.getElementById('log');const prompt=document.getElementById('prompt');
let x=250,y=470;const keys=new Set();const props=[...document.querySelectorAll('.prop')];const visited=new Set();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function rect(el){return {x:el.offsetLeft,y:el.offsetTop,w:el.offsetWidth,h:el.offsetHeight}}
function nearProp(){const px=x+21,py=y+43;let best=null,bd=1e9;for(const p of props){const r=rect(p);const cx=p.parentElement.offsetLeft+r.x+r.w/2,cy=p.parentElement.offsetTop+r.y+r.h/2;const d=Math.hypot(px-cx,py-cy);if(d<bd){bd=d;best=p}}return bd<120?best:null}
function move(){const speed=keys.has('shift')?5.2:3.1;if(keys.has('w')||keys.has('arrowup'))y-=speed;if(keys.has('s')||keys.has('arrowdown'))y+=speed;if(keys.has('a')||keys.has('arrowleft'))x-=speed;if(keys.has('d')||keys.has('arrowright'))x+=speed;x=clamp(x,60,1695);y=clamp(y,130,565);player.style.left=x+'px';player.style.top=y+'px';const vw=world.clientWidth,vh=world.clientHeight;const cx=clamp(x-vw/2+120,0,1800-vw),cy=clamp(y-vh/2+60,0,760-vh);camera.style.transform=`translate(calc(-50% - ${cx}px),calc(-50% - ${cy}px))`;const p=nearProp();prompt.textContent=p?'E — '+p.textContent:'WASD 移動｜靠近物件按 E';requestAnimationFrame(move)}
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e'){const p=nearProp();if(p){visited.add(p.textContent);log.textContent='互動：'+p.textContent+'｜已探索 '+visited.size+' 個重點';p.animate([{transform:'scale(1)'},{transform:'scale(1.06)'},{transform:'scale(1)'}],{duration:260})}}if(e.key.toLowerCase()==='r'){x=250;y=470;visited.clear();log.textContent='已重置'}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));world.addEventListener('pointerdown',()=>world.focus());
world.focus();move();
const foodButtons=[...document.querySelectorAll('[data-food]')],boardFood=document.getElementById('boardFood'),cutBtn=document.getElementById('cutBtn'),heatBtn=document.getElementById('heatBtn'),addBtn=document.getElementById('addBtn'),stirBtn=document.getElementById('stirBtn'),plateBtn=document.getElementById('plateBtn'),wokContents=document.getElementById('wokContents'),recipeLog=document.getElementById('recipeLog'),flame=document.getElementById('flame'),cookObjective=document.getElementById('cookObjective');
const foodNames={tofu:'豆腐',pork:'絞肉',douban:'豆瓣醬',garlic:'蒜',pepper:'花椒',scallion:'青蔥'};let selectedFood=null,prepped=new Set(),heated=false,inWok=[],stirs=0;
function cookLog(t){if(recipeLog.children.length===1&&recipeLog.textContent.includes('等待'))recipeLog.innerHTML='';const li=document.createElement('li');li.textContent=t;recipeLog.append(li);recipeLog.scrollTop=recipeLog.scrollHeight}
foodButtons.forEach(b=>b.addEventListener('click',()=>{foodButtons.forEach(x=>x.classList.remove('is-selected'));b.classList.add('is-selected');selectedFood=b.dataset.food;boardFood.textContent=foodNames[selectedFood]+' 已放上砧板';cutBtn.disabled=false;cookObjective.textContent='備料：'+foodNames[selectedFood]}));
cutBtn.addEventListener('click',()=>{if(!selectedFood)return;prepped.add(selectedFood);document.querySelector('[data-food="'+selectedFood+'"]').classList.add('is-prepped');boardFood.textContent=foodNames[selectedFood]+' 已備妥';cookLog('備料完成：'+foodNames[selectedFood]);addBtn.disabled=!heated;cutBtn.disabled=true});
heatBtn.addEventListener('click',()=>{heated=!heated;flame.classList.toggle('is-on',heated);heatBtn.textContent=heated?'關火':'開火';cookLog(heated?'炒鍋升溫':'關火');addBtn.disabled=!heated||prepped.size===0;cookObjective.textContent=heated?'鍋熱了：把備好的材料下鍋':'先開火'});
addBtn.addEventListener('click',()=>{if(!heated||prepped.size===0)return;for(const id of prepped){if(!inWok.includes(id))inWok.push(id)}wokContents.textContent=inWok.map(x=>foodNames[x]).join('＋');cookLog('下鍋：'+wokContents.textContent);stirBtn.disabled=false;plateBtn.disabled=inWok.length<4;cookObjective.textContent='觀察鍋內，開始翻炒'});
stirBtn.addEventListener('click',()=>{stirs++;wokContents.animate([{transform:'translateX(-8px) rotate(-2deg)'},{transform:'translateX(8px) rotate(2deg)'},{transform:'none'}],{duration:300});cookLog('翻炒 '+stirs+' 次');if(stirs>=3&&inWok.length>=4){plateBtn.disabled=false;cookObjective.textContent='香氣出來了，可以盛盤'}});
plateBtn.addEventListener('click',()=>{if(plateBtn.disabled)return;wokContents.textContent='麻婆豆腐完成';cookLog('完成：麻婆豆腐盛盤');cookObjective.textContent='下一步：端回上方診間給病人';plateBtn.disabled=true;stirBtn.disabled=true;addBtn.disabled=true});
